title: Kleyton Polzonoff
logo: profile/profile.png
theme: jekyll-theme-minimal

# Custom CSS
stylesheets:
  - "/assets/css/custom-styles.css"

# Site Settings
locale: "en-US"
description: "Personal description"
url: https://kleyton-polzonoff.github.io
baseurl: ""

# Author Information
author:
  name: "Kleyton Polzonoff"
  bio: "Personal description"
  avatar: "profile/profile.png"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Output Settings
permalink: "/:categories/:title/"
timezone: Etc/UTC

# Exclude unnecessary files
exclude:
  - ".git"
  - ".github"
  - "_site"
  - "node_modules"
  - "README.md"
